-- Operations Hub - persistent production performance telemetry
-- Safe to run more than once.
-- This stores only sanitized profiler metadata; no request bodies, cookies,
-- query values, user IDs, or authentication tokens are written by the app.

create table if not exists public.erp_performance_samples (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category text not null,
  name text not null,
  duration_ms double precision not null default 0,
  ok boolean not null default true,
  status integer not null default 0,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists idx_erp_performance_samples_created_at
  on public.erp_performance_samples (created_at desc);

create index if not exists idx_erp_performance_samples_operation_created
  on public.erp_performance_samples (category, name, created_at desc);

alter table public.erp_performance_samples enable row level security;

-- The table is deliberately server-only. The Next.js runtime uses a service
-- credential for writes/reads; browser anon/authenticated clients get no table
-- privileges and no RLS policy is created for them.
revoke all on table public.erp_performance_samples from anon, authenticated;
grant select, insert, delete on table public.erp_performance_samples to service_role;
grant usage, select on sequence public.erp_performance_samples_id_seq to service_role;

-- Keep the table bounded without requiring a cron job. Cleanup runs only once
-- every 500 inserted samples and happens in telemetry work after the response.
create or replace function public.erp_performance_samples_retention_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if mod(new.id, 500) = 0 then
    delete from public.erp_performance_samples
    where created_at < now() - interval '7 days';
  end if;
  return null;
end;
$$;

drop trigger if exists trg_erp_performance_samples_retention on public.erp_performance_samples;
create trigger trg_erp_performance_samples_retention
after insert on public.erp_performance_samples
for each row execute function public.erp_performance_samples_retention_trigger();

create or replace function public.erp_clear_performance_samples()
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  removed_count bigint := 0;
begin
  delete from public.erp_performance_samples;
  get diagnostics removed_count = row_count;
  return removed_count;
end;
$$;

create or replace function public.erp_prune_performance_samples(p_keep_hours integer default 168)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  removed_count bigint := 0;
  keep_hours integer := greatest(1, least(coalesce(p_keep_hours, 168), 24 * 90));
begin
  delete from public.erp_performance_samples
  where created_at < now() - make_interval(hours => keep_hours);
  get diagnostics removed_count = row_count;
  return removed_count;
end;
$$;

revoke all on function public.erp_clear_performance_samples() from public;
revoke all on function public.erp_prune_performance_samples(integer) from public;
grant execute on function public.erp_clear_performance_samples() to service_role;
grant execute on function public.erp_prune_performance_samples(integer) to service_role;

-- Verification result shown directly in the SQL editor.
select
  to_regclass('public.erp_performance_samples') is not null as telemetry_table_installed,
  to_regprocedure('public.erp_clear_performance_samples()') is not null as clear_rpc_installed,
  to_regprocedure('public.erp_prune_performance_samples(integer)') is not null as prune_rpc_installed;
